name: "godot-release"

on:
  workflow_run:
    workflows: ["godot-ci.yml"]
    tags: v[0-9]+.[0-9]+.[0-9]+
    types: 
      - completed

jobs:
  publish-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux, windows, mac ]

    steps:
    - name: Download client
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: godot-ci.yml
        workflow_conclusion: success
        commit: ${{ github.sha }}
        event: push
        name: ${{ matrix.platform }}  
        path: DisasterArena

    - name: Set version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Set filename
      run: echo "FILENAME=DisasterArena-${{ env.VERSION }}-${{ matrix.platform }}" >> $GITHUB_ENV

    - name: Zip client
      run: zip -q -r ${{ env.FILENAME }}.zip DisasterArena

    - name: Publish to github release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.FILENAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-ghpages:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.
